Feature: Task 3 - buttons [ref: task-3]
js-tasks-ru/htmlcss-20230411_alexandr-baranchugov pull request #4
Opened 2023-04-27 01:48 UTC by ABaranchugov

2023-04-27 01:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-27 01:50 UTC, ABaranchugov commented
Не стал задавать фиксированную ширину кнопки = 189пкс, ибо считаю, что размер кнопки нужно определять по содержимому или исходя из контекста встраивания

2023-04-27 02:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-28 14:25 UTC, GSemikozov requested changes

2023-04-28 14:25 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2023-04-28 14:25 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 0 40px;
лучше все-таки указывать сверху-снизу, поскольку когда через модификатор меняем на display: block - верстка поедет

2023-04-29 18:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-29 18:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-02 22:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-03 13:58 UTC, GSemikozov requested changes

2023-05-03 13:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
соответственно cursor: not-allowed; лишний

2023-05-03 13:58 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <div class="accordions">
именно это - блок accordion

2023-05-03 13:58 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details class="accordion">
а это - его секции, например accordion__item или accordion__section

2023-05-04 14:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-04 14:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-04 14:52 UTC, ABaranchugov commented
Поправил

2023-05-04 15:10 UTC, GSemikozov requested changes

2023-05-04 15:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 720px;
лишнее

2023-05-04 15:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 40px;
лишнее

2023-05-04 15:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px 24px;
`24 32`

2023-05-05 12:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-06 10:32 UTC, GSemikozov approved these changes

2023-05-06 10:32 UTC, merged